module.exports = [
  'I only know 25 letters of the alphabet. I don\'t know y.',
  'Why did the invisible man turn down the job offer? He couldn\'t see himself doing it.',
  '<strong>Question:</strong> What does a lemon say when it answers the phone?<br/><strong>Answer:</strong> Yellow!',
  'Where do bad rainbows go? Prism. It is just a light sentence.',
  'Why can’t you send a duck to space? Because the bill would be astronomical.',
  'Want to know why nurses like red crayons? Sometimes they have to draw blood.',
  'Why did the scarecrow win an award? Because he was the best in his field.',
  'Why didn’t Han Solo enjoy his steak dinner? It was Chewie.',
  'When I was a kid, my dad got fired from his job as a road worker for theft. I refused to believe he could do such a thing, but when I got home, the signs were all there.',
  'What’s orange and sounds like a parrot? A Carrot.',
  'I was wondering why this frisbee kept looking bigger and bigger. And then it hit me!',
  'What do you call an alligator in a vest? An investigator.',
  'I used to be addicted to the hokey pokey. Then I turned myself around.',
  'What do you call a fake noodle? An impasta.',
  '<strong>Question:</strong> Why did the cat sit on the computer?<br/><strong>Answer:</strong> To keep an eye on the mouse',
  'Autocorrect has become my worst enema.',
  '<strong>Question:</strong> Why do bees have sticky hair?<br/><strong>Answer:</strong> Because they use a honeycomb.',
  'There’s a band called 1023MB. They haven’t had any gigs yet.',
  '"Knock, knock. Who\'s there?"<br/>very long pause...<br/>"Java."',
  'An SEO expert walks into a bar, bars, pub, tavern, public house, Irish pub, drinks, beer, alcohol',
  'I would tell you a UDP joke, but you might not get it',
  '8 bytes walk into a bar, the bartenders asks "What will it be?"<br/>One of them says, "Make us a double."',
];